# Generated by Django 4.0.5 on 2022-06-15 06:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('project_id', models.CharField(default='PROJ_S62QA302AD', editable=False, max_length=20)),
            ],
            options={
                'db_table': 'PROJECT',
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('videos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('selected_images', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('selected_videos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('selected_files', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('access_permissions', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=30), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'PROJECT_MEDIA',
            },
        ),
    ]
