# Generated by Django 4.0.5 on 2022-06-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default='PROJ_5KM4YC89BY', editable=False, max_length=20),
        ),
    ]
