# Generated by Django 4.0.5 on 2022-06-17 13:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_alter_company_company_id'),
        ('project', '0003_alter_project_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmedia',
            name='access_permissions',
        ),
        migrations.AddField(
            model_name='project',
            name='access_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default='PROJ_JQ4233355W', editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('client_id', models.CharField(default='CLI_Z4L74471S3', editable=False, max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ManyToManyField(blank=True, to='project.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CLIENT',
            },
        ),
    ]
