# Generated by Django 4.0.5 on 2022-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default='COMP_SL0S8RYI2D', editable=False, max_length=20),
        ),
    ]
