# This is a basic workflow to help you get started with Actions

name: Dango dev CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USERNAME }}
        key: ${{ secrets.DEV_SERVER_PRIVATE_KEY }}
        port: 22
        script: |
          cd picman_studio_backend
          git pull origin main
          pm2 restart node1

VAKkB5sJqQ+4LnLVxZY19Ybv3FGg/TQSUcJ+sGesfy3QiHMhuKoQY590OZbgg+Tbz9f381
qT6eC/8rAIxVu+QodgOHrVA/hQBjoS/eg8qNJKXeoo2KCssAWVvz+zPPGrs7t4ji6pdzrw
gmkLip++25k+amLBXW6HMAAAADAQABAAACAGnkAxHoQmlnyr2n87rhLjS7109fUlg5i4WO
PKTzGW31SI9gnPJfggJz6zhZXl7G1SZZzyosxQU9geyxEiWL/p/cplcRmt7mk1B8cp2NZf
RBOZs6SWuF7N4V157hTuSAHksd0I1ECeTmMesE9kwL5+8eZROQ/iTGmROIs9BbFwv/sE0z
ywGFsVwtvPiF5NTb5XUbYNGrPvr6cLwzqwVy8XLK5ZXQMOOJj3XB+urC5ZNmwVuHTJJp3D
NRPVcCI61POCp3T7Iwcq0sZ76ZCZ4yGHCV47ipPWqoNy5TfO6zgA3qW8eq8wo0cu9VuMvQ
aSlTJE78INDV+7jxaNfQ0AxnMfGq3xiUpO1IGcOSHfoMnmYbZnR9JuwZIBBBHZuQMSFatC
4pONQUbtgbM++PRhTPjK1D7he3mXCFQTzqJD13UZhOf01JNlIOSHb1Yqh6+LnOqpvPp5he
7Eyjgi7jCQXo+6M5udHRxJX+YQWCq8ILoWiOnxUporyhNyJedtHH1Z5kJfZeMBFSVcc0qG
k96ISqxZKxngZ/zCLQg3tJ+iW7O43VWFqrsGScw9D5G2FXDSpTELdbEJH6KWJomuobvq/U
HA1QQsZlu4DTz9UDHeVkIYpgTIAU7SxzHKdF518nrJdPHdtuZlygxEi6iRE0KpaCY4TMXh
3ToQwJ5hkQZgU5pWspAAABAGMCAQDb2fa2u3WjukYdqX5Jqz4Id2EG0ZCqRNUi+yIgVGj/
GKC2jPc7c+LNLITZJVNgjYL6vQ/k1BFGYp6HtuP9HkM7xM8e9U94p6kidRsSY1b4tEWYpf
iB4iNrEWMfodX27+K2yS5n48PCZg2OVDoazp1gxnHAlhl9O36lznacFHP2SfJS0sJLE8pg
rFzPGSZ4NlX/BRtPUq9907CzmFq4p86IJUNfOA6ScQAoVz9RzAa0gPic8VGP3sDV4bAthX
86NLpnriqIp3Z12RGYosrY+HQuF3+kfJ6Q9QqbDH/TSdBKRS3+YyaIIZl7kLKNVB6NXW5B
dF/z/AnUjx9sH9wAAAEBAOe3kMpk04XgBTyEOvASX1qvy49uEQpqSzcfwlPnWU2h9javxd
+rJwdk++OZJk6VCzDQvSmGoLmBV+NlNJEHkaKEn+oMM2jsl0zwfO06lDQr9CSelegYO4Yj
lBEm+SUW4TiV+/GP1HN6HwOAhQrRe93MzZVJENiXRPf8xCLiVi94Q3/kwQcFB8TayGsv/4
5PZG/BUfHedMOka0L012HgRBUWOsYIjYEFhVDhIKV7i4mgjyvpqGeWoJFpP0bVx+x2h6uQ
x8wwytkzGMNFlCG/ln7yx63G06mt58iPEhvmmZc/2tnDId2VDxyOZiPdGRwklp5qCn6IEm
c5r1PKLP/Io1UAAAEBAM+PC8dedv1ULQwmDCBmU8QW/0yxIgPq+3tvVR5d5Yjj9TxMrwmk
kS/12vj3QpfvqD0CWNMjWr9z+128I6QZo0mMwhpeSaMioLMDiRPhPmJGHHqaDj60juC6zp
AKCcgNNCLskmJPDl7SBnI6lc8S/h1CyW3JohDK2kVN471fygrCdwVVcgB+eqCSao5mJok3
MP8WI2VORo6FBXH+TP8C7YhKgkkD8Lholjc74NzTU/D+fVz/XBnfAuRIzyIaERtnzMKnVh
VMUqXI4vOaL7uYWAAdUMiLbdg4cwyLJqNUrc9fJZHVg4Y/abinQzv7kEm/9/WCGaTqhTAw
KNWJHnna7KcAAAAbYWtoaWxlZGF0aGFkYW4wMDdAZ21haWwuY29t
-----END OPENSSH PRIVATE KEY-----